FROM openjdk:17-slim

WORKDIR /app

COPY . .
COPY .env .

RUN apt-get update && apt-get install maven -y

RUN mvn clean package -DskipTests
EXPOSE 8081

CMD ["java", "-jar", "target/api-0.0.1-SNAPSHOT.jar"]

