version: '3.1'

services:


  api:
    restart: always
    build:
      dockerfile: dockerfile
    ports:
      - ${PORT}:${PORT}
    networks:
      - mediacodec-user-manager
    depends_on:
      - db
      - messaging
      - cache
    volumes:
      - ./uploads:/app/public/files
  db:
    image: mysql:8.0.31
    restart: always
    hostname: mediacodec-data
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASS}
      MYSQL_DATABASE: ${MYSQL_DATA}
    volumes:
      - ./database:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - mediacodec-user-manager

  phpmyadmin:
    image: phpmyadmin
    ports:
      - "8000:80"
    environment:
      - PMA_ARBITRARY=1
    networks:
      - mediacodec-user-manager

  cache:
    image: redis:latest
    restart: always
    ports:
      - "${REDIS_PORT}:6379"
    networks:
      - mediacodec-user-manager

  messaging:
    image: rabbitmq:management
    restart: always
    hostname: mediacodec-amqp
    ports:
      - '5673:5672'
      - '15673:15672'
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq

    environment:
      RABBITMQ_DEFAULT_USER: ${MQ_USER}
      RABBITMQ_DEFAULT_PASS: ${MQ_PASS}
    networks:
      - mediacodec-user-manager

networks:
  mediacodec-user-manager:
    driver: bridge
